### ISSUE TITLE
Alternatives to "=>"?

### ISSUE THREAD

**Issue by ForgivenNin** [cyruscook/LoadingScreen#1]
Though it works on HTML, when the script is moved/translated into a .js file, there is apparently a syntax error for ```=>``` as an operator.

```
addEventListener("pageshow",()=>{
```

```
var e=()=>{
```

```
Date.now()-LSDate>=2990?e():setTimeout(e,Date.now()+2990-Date.now())
```
_(I changed the time, but I know that likely didn't affect anything.)_
Are there any alternatives that can replace that without breaking the entire thing?

If you want to see how I'm using this, [here's my fork](https://github.com/ForgivenNin/funnyLoadingScreen).

**Comment by cyruscook** [comment]
This is because Arrow Syntax ( `()=>{}` ) are a part of es6, so you are probably running it in an old browser. You can use babel js (https://babeljs.io/) to downgrade the javascript to make it more compatible.

The reason I am using arrow syntax is that it uses less space, and obviously fast loading times are a must for a loading screen.

**Comment by ForgivenNin** [comment]
What is es6? 
It is helpful to know that I may be on an old browser, though. _It's Safari Version 12.1.1 (14607.2.6.1.1)_
My preference is that it doesn't have any dependencies, but thanks for info!

**Comment by cyruscook** [comment]
ES6 stands for ECMAScript 6. EMCAScript is kind of like the rulebook for JavaScript that defines that you can write a function as so: `function hello() { return "goodbye"; }`, and each time it gets updated they add another number onto the version. ES6 has added many updates, one of those being arrow functions, so now the rulebook specifies that a function can not only be written as I previously showed but also like so: `var hello = () => "goodbye";`. Both examples will do exactly the same thing, however arrow functions look much cleaner and take up much less space.

I'm not familiar with Safari, so I'm not sure if that is an up to date version, however in general even in the up to date versions safari is not known for it's compatibility, I'd recommend installing Chrome.

It will not need any dependencies, simply change your current code in ls-autosetup.js to the code I pasted above, nothing else is required, babel is what is called a pre-processor, meaning that it will process the code before it is sent to the client therefore no dependencies.
